<html>
<head>
    <title>Test</title>
</head>
<body>
<p>
<h1>Wyszukany produkt po ID: </h1>
<h2>Product producer: ${mobile.producer}</h2>
<p>Product UUID: ${mobile.id}</p>
<p>Product model: ${mobile.model}</p>
<p>Product scrren: ${mobile.scrren}</p>
<p>Product price: ${mobile.price}</p>
<p>Product data: ${mobile.createData}</p>
<p>Product status: ${mobile.status}</p>
<p>Product promoted: ${mobile.isPromoted}</p>

</p>

</body>
</html>
